language: node_js
node_js:
  - 6
  - 8
  - 10
sudo: false
before_install:
  - curl -L https://unpkg.com/@pnpm/self-installer | PNPM_VERSION=2.17.0 node
install:
  - pnpm i
script:
  - npm t
notifications:
  email: false
